apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-custom-app
  namespace: argocd 
spec:
  project: default
  source:
    # 1. Point this to YOUR new GitHub URL!
    repoURL: 'https://github.com/himanshuvb/gitops-tool.git'
    targetRevision: HEAD
    # 2. We put the YAML in the root of the folder, so we use a dot
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true